# Generated by Django 3.0.3 on 2020-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('blurb', models.CharField(max_length=150)),
                ('pov', models.CharField(max_length=10)),
                ('setting', models.CharField(max_length=10000)),
                ('theme', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
