# Generated by Django 3.0.3 on 2020-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_auto_20200218_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plot',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
