# Generated by Django 3.0.3 on 2020-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0004_auto_20200219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='created_at',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
