# Generated by Django 3.0.3 on 2020-02-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0008_auto_20200222_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Plot'),
        ),
    ]
